AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  SidecarManagerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layer

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs
      Handler: index.handler
      Runtime: nodejs20.x
      Layers:
        - !Ref SidecarManagerLayer
